/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HjyService_CONSTANTS_H
#define HjyService_CONSTANTS_H

#include "HjyService_types.h"



class HjyServiceConstants {
 public:
  HjyServiceConstants();

};

extern const HjyServiceConstants g_HjyService_constants;



#endif
